<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ConferenceHallBooking.Domain\ConferenceHallBooking.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Abstractions\" />
    <Folder Include="Mapping\" />
    <Folder Include="DTOs\" />
    <Folder Include="Validators\" />
    <Folder Include="Services\" />
  </ItemGroup>

</Project>
