<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <AdditionalFiles Remove="C:\Users\OlehKozlovskyi\AppData\Roaming\SonarLint for Visual Studio\.global\csharp\SonarLint.xml" />
  </ItemGroup>

</Project>
